# Prometheus Alert Rules
# Production alerting configuration for LUMINES/WIS2L

groups:
  # Critical Alerts (P0)
  - name: critical
    interval: 30s
    rules:
      # Service Down
      - alert: ServiceDown
        expr: up{job="lumines-web"} == 0
        for: 1m
        labels:
          severity: critical
          priority: P0
        annotations:
          summary: "LUMINES web service is down"
          description: "Service {{ $labels.instance }} has been down for more than 1 minute."

      # Database Down
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          priority: P0
        annotations:
          summary: "PostgreSQL database is down"
          description: "Database {{ $labels.instance }} has been down for more than 1 minute."

      # High Error Rate
      - alert: HighErrorRate
        expr: |
          rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
          priority: P0
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors/second (threshold: 0.1)"

      # Database Connection Pool Exhausted
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          pg_stat_database_numbackends / pg_settings_max_connections > 0.95
        for: 5m
        labels:
          severity: critical
          priority: P0
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Database connections at {{ $value | humanizePercentage }} (threshold: 95%)"

  # Warning Alerts (P1)
  - name: warnings
    interval: 1m
    rules:
      # High Response Time
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
          priority: P1
        annotations:
          summary: "High response time detected"
          description: "p95 response time is {{ $value }}s (threshold: 1s)"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: |
          100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          priority: P1
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} (threshold: 80%)"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
          priority: P1
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} (threshold: 85%)"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: |
          (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
          priority: P1
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value | humanizePercentage }} (threshold: 85%)"

      # Slow Database Queries
      - alert: SlowDatabaseQueries
        expr: |
          rate(pg_stat_statements_mean_exec_time[5m]) > 1
        for: 10m
        labels:
          severity: warning
          priority: P1
        annotations:
          summary: "Slow database queries detected"
          description: "Average query time is {{ $value }}s (threshold: 1s)"

      # Redis Memory High
      - alert: RedisMemoryHigh
        expr: |
          redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 10m
        labels:
          severity: warning
          priority: P1
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is {{ $value | humanizePercentage }} (threshold: 90%)"

  # Info Alerts (P2)
  - name: info
    interval: 5m
    rules:
      # Deployment Event
      - alert: DeploymentEvent
        expr: |
          changes(up{job="lumines-web"}[5m]) > 0
        for: 0m
        labels:
          severity: info
          priority: P2
        annotations:
          summary: "Service deployment detected"
          description: "Service {{ $labels.instance }} was deployed or restarted"

      # Scaling Event
      - alert: ScalingEvent
        expr: |
          changes(kube_deployment_spec_replicas[5m]) > 0
        for: 0m
        labels:
          severity: info
          priority: P2
        annotations:
          summary: "Service scaling detected"
          description: "Deployment {{ $labels.deployment }} replicas changed"

