export interface ExportTemplate {
  name: string;
  description: string;
  includeReadme: boolean;
  includeAssemblyDefinition: boolean;
  includePackageManifest: boolean;
  folderStructure: string[];
}

export const DEFAULT_TEMPLATE: ExportTemplate = {
  name: "Standard",
  description: "Basic Unity script export with Assets/Scripts structure",
  includeReadme: false,
  includeAssemblyDefinition: false,
  includePackageManifest: false,
  folderStructure: ["Assets", "Scripts"],
};

export const PACKAGE_TEMPLATE: ExportTemplate = {
  name: "Unity Package",
  description: "Full Unity package with manifest and assembly definitions",
  includeReadme: true,
  includeAssemblyDefinition: true,
  includePackageManifest: true,
  folderStructure: ["Packages", "com.spark.generated", "Runtime"],
};

export const ORGANIZED_TEMPLATE: ExportTemplate = {
  name: "Organized",
  description: "Organized structure with separate folders for different script types",
  includeReadme: true,
  includeAssemblyDefinition: false,
  includePackageManifest: false,
  folderStructure: ["Assets", "Scripts", "Generated"],
};

export function generateReadme(scriptNames: string[]): string {
  return `# SPARK Generated Scripts

This package contains Unity C# scripts generated by SPARK AI.

## Scripts Included

${scriptNames.map(name => `- **${name}.cs**`).join('\n')}

## Installation

1. Extract this ZIP file
2. Copy the contents into your Unity project
3. Unity will automatically import the scripts

## Usage

The generated scripts are ready to use in your Unity project. Simply:
1. Attach scripts to GameObjects in your scene
2. Configure any public properties in the Inspector
3. Enter Play mode to see them in action

## Generated by SPARK

SPARK is an AI-powered Unity C# script generator that creates production-ready code from natural language descriptions.

Visit: https://spark.dev for more information

---
*Generated on ${new Date().toLocaleDateString()}*
`;
}

export function generateAssemblyDefinition(packageName: string): string {
  return JSON.stringify({
    name: packageName,
    rootNamespace: packageName.replace(/[^a-zA-Z0-9]/g, ''),
    references: [],
    includePlatforms: [],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false
  }, null, 2);
}

export function generatePackageManifest(packageName: string, scriptNames: string[]): string {
  return JSON.stringify({
    name: `com.spark.${packageName.toLowerCase().replace(/[^a-z0-9]/g, '')}`,
    version: "1.0.0",
    displayName: `SPARK - ${packageName}`,
    description: `Unity scripts generated by SPARK AI: ${scriptNames.join(', ')}`,
    unity: "2020.3",
    keywords: [
      "spark",
      "ai-generated",
      "unity",
      "scripts"
    ],
    author: {
      name: "SPARK AI",
      url: "https://spark.dev"
    }
  }, null, 2);
}
